### ISSUE TITLE
Request Features FadeIn - FadeOut + PTT mode

### ISSUE THREAD

**Issue by e4rthdog** [razorlikes/AppVolumeHotkeys#1]
Hi!
I have been searching something like this and i am glad i found it.

Though i need PTT functionality instead of TOGGLE. I would like to be able to assign the hotkey and mute while holding it. You could add a checkbox to switch between toggle/ptt mode.

Second request would be to smooth out the muting function by fading it in and out.

**Comment by razorlikes** [comment]
Hey, always nice to hear that someone else can get some use out of my projects!

I will definitely look into your requests, probably around the weekend since I have a lot of stuff for uni to sort out right now but expect an update soon. A push-to-mute function actually sounds really useful.

As for the smoothing, I'll look into that too but I have some concerns about the performance of the windows mixer considering the amount of volume adjustments that would have to be made for a _smooth_ transition. It's also more of a "cosmetic" thing so not top priority right now.

**Comment by e4rthdog** [comment]
PTT use case scenario for my case is to use it while streaming. I want to lower the volume of my music/game sounds e.t.c when i talk to microphone. So i would assign the same key as my mic PTT.

I second your concerns about performance for the smoothing out, but an alternative would be not to mute but to be able to specify the amount of volume decrease.

I will try to contribute some code for the above, for you to check it out.

Thank you!
